const data = {
    produtos: [
      {
        _id:'1',
         name: 'Teclado Mecânico GK61',
         category: 'Periféricos',
         image: '/images/teclado.jpg',
         price: 599,
         brand: 'Geek',
         rating: 5,
         numReviews: 10,
         description:'Produto de excelente qualidade',
       },
       {
          _id:'2',
           name: 'Cadeira Gamer Alpha',
           category: 'Cadeiras',
           image: '/images/cadeira.jpg',
           price: 1270,
           brand: 'Alpha',
           rating: 5,
           numReviews: 10,
           description:'Melhor cadeira gamer do mercado',
         },
         {
          _id:'3',
           name: 'Microfone HyperX Quadcast',
           category: 'Periféricos',
           image: '/images/quadcast.jpg',
           price: 999,
           brand: 'HyperX',
           rating: 5,
           numReviews: 10,
           description:'Este microfone gamer oferece de forma independente todos os recursos necessários para uma ótima gravação',
         },
         {
          _id:'4',
           name: 'Mouse G Pro Wireless',
           category: 'Periféricos',
           image: '/images/mouse.png',
           price: 899,
           brand: 'Logitech',
           rating: 5,
           numReviews:  10,
           description:'O PRO Wireless gaming mouse foi concebido para oferecer um desempenho de ponta e inclui as mais recentes e avançadas tecnologias disponíveis',
         },
         {
          _id:'5',
           name: 'Headset HyperX Cloud II',
           category: 'Periféricos',
           image: '/images/h7.jpg',
           price: 599,
           brand: 'HyperX',
           rating: 5,
           numReviews: 10,
           description:'Com o Headset Gamer HyperXCloud II você tem a garantia de uma excelente experiência de jogo',
         }, 
     ],    
  };
  export default data;